version: '3'
#services:
#  db:
#    image: postgres:13.2
#    container_name: docker-postgres-db
#    ports:
#      - 5432:5432
#    volumes:
#      - volume:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=spring_boot_postgres_db


services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_boot_postgres_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
